# Generated by Django 4.2.7 on 2025-06-14 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Actor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("patient_id", models.CharField(db_index=True, max_length=100)),
                ("name", models.CharField(db_index=True, default="-", max_length=200)),
                ("dob", models.DateField(db_index=True)),
                ("contact", models.CharField(db_index=True, max_length=100, null=True)),
                ("address", models.CharField(db_index=True, max_length=200, null=True)),
                ("gender", models.CharField(db_index=True, max_length=10, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name="Workspace",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Visit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scheduled_at", models.DateTimeField(blank=True, db_index=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "actor_assigned",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actor_visits",
                        to="tumor_api.actor",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="patient_visits",
                        to="tumor_api.patient",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="patient",
            name="workspace",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="workspace",
                to="tumor_api.workspace",
            ),
        ),
        migrations.CreateModel(
            name="Observation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("focus", models.CharField(db_index=True, max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="patient_observations",
                        to="tumor_api.patient",
                    ),
                ),
                (
                    "visit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="visit_observations",
                        to="tumor_api.visit",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MedicationStatement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("medication_text", models.CharField(db_index=True, max_length=200)),
                ("dosage", models.CharField(db_index=True, max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="patient_medication_statements",
                        to="tumor_api.patient",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Immunization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vaccine", models.CharField(db_index=True, max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="patient_immunizations",
                        to="tumor_api.patient",
                    ),
                ),
                (
                    "visit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="visit_immunizations",
                        to="tumor_api.visit",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image_id", models.CharField(db_index=True, max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="patient_images",
                        to="tumor_api.patient",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DiagnosticReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("free_text_report", models.CharField(max_length=400)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="patient_reports",
                        to="tumor_api.patient",
                    ),
                ),
                (
                    "visit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="visit_reports",
                        to="tumor_api.visit",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CarePlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("care_plan_provided", models.CharField(db_index=True, max_length=300)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="patient_care_plans",
                        to="tumor_api.patient",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="visit",
            index=models.Index(
                fields=["patient", "scheduled_at"],
                name="tumor_api_v_patient_eafb3e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="visit",
            index=models.Index(
                fields=["patient", "created_at"], name="tumor_api_v_patient_b9caf4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="visit",
            index=models.Index(
                fields=["actor_assigned", "scheduled_at"],
                name="tumor_api_v_actor_a_f54aba_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="patient",
            index=models.Index(
                fields=["workspace", "patient_id"],
                name="tumor_api_p_workspa_e82706_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="patient",
            index=models.Index(
                fields=["workspace", "name"], name="tumor_api_p_workspa_627314_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="patient",
            index=models.Index(
                fields=["workspace", "dob"], name="tumor_api_p_workspa_ee06ec_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="patient",
            index=models.Index(
                fields=["workspace", "gender"], name="tumor_api_p_workspa_dd3e52_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="observation",
            index=models.Index(
                fields=["patient", "focus"], name="tumor_api_o_patient_b8c963_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="observation",
            index=models.Index(
                fields=["patient", "created_at"], name="tumor_api_o_patient_e9d061_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="observation",
            index=models.Index(
                fields=["visit", "focus"], name="tumor_api_o_visit_i_c44aab_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="medicationstatement",
            index=models.Index(
                fields=["patient", "medication_text"],
                name="tumor_api_m_patient_d62adf_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="medicationstatement",
            index=models.Index(
                fields=["patient", "created_at"], name="tumor_api_m_patient_5ce88f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="immunization",
            index=models.Index(
                fields=["patient", "vaccine"], name="tumor_api_i_patient_2599d8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="immunization",
            index=models.Index(
                fields=["patient", "created_at"], name="tumor_api_i_patient_b84401_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="immunization",
            index=models.Index(
                fields=["visit", "vaccine"], name="tumor_api_i_visit_i_b7e6f2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="image",
            index=models.Index(
                fields=["patient", "image_id"], name="tumor_api_i_patient_261f39_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="image",
            index=models.Index(
                fields=["patient", "created_at"], name="tumor_api_i_patient_9a7509_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="diagnosticreport",
            index=models.Index(
                fields=["patient", "created_at"], name="tumor_api_d_patient_35ba99_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="diagnosticreport",
            index=models.Index(
                fields=["visit", "created_at"], name="tumor_api_d_visit_i_cfe52e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="careplan",
            index=models.Index(
                fields=["patient", "created_at"], name="tumor_api_c_patient_43d368_idx"
            ),
        ),
    ]
