# Generated by Django 5.2.3 on 2025-06-14 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tumor_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='display_name',
            field=models.CharField(db_index=True, default='actor_name', max_length=200),
        ),
        migrations.AddField(
            model_name='diagnosticreport',
            name='status',
            field=models.CharField(choices=[('normal', 'Normal'), ('abnormal', 'Abnormal')], db_index=True, default='normal', max_length=10),
        ),
        migrations.AddField(
            model_name='workspace',
            name='display_name',
            field=models.CharField(db_index=True, default='workspace', max_length=200),
        ),
    ]
