# Generated by Django 5.2.3 on 2025-06-14 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tumor_api', '0002_actor_display_name_diagnosticreport_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhysicianNotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.CharField(db_index=True, max_length=300)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_physician_notes', to='tumor_api.patient')),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visit_physician_notes', to='tumor_api.visit')),
            ],
            options={
                'indexes': [models.Index(fields=['patient'], name='tumor_api_p_patient_97e4c0_idx')],
            },
        ),
    ]
