# Generated by Django 5.2.3 on 2025-06-14 17:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tumor_api", "0005_aireport_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="added_to_tumor_board",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
