# Generated by Django 5.2.3 on 2025-06-14 12:54

import django.db.models.deletion
import tumor_api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tumor_api', '0003_physiciannotes'),
    ]

    operations = [
        migrations.CreateModel(
            name='DicomFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=tumor_api.models.get_dicom_upload_path)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='ImageSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=200)),
                ('key_slices', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
        ),
        migrations.RemoveIndex(
            model_name='image',
            name='tumor_api_i_patient_261f39_idx',
        ),
        migrations.RemoveField(
            model_name='image',
            name='image_id',
        ),
        migrations.AddField(
            model_name='image',
            name='file',
            field=models.FileField(null=True, upload_to=tumor_api.models.get_general_media_upload_path),
        ),
        migrations.AddField(
            model_name='image',
            name='visit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='tumor_api.visit'),
        ),
        migrations.AlterField(
            model_name='image',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='tumor_api.patient'),
        ),
        migrations.AddField(
            model_name='imageseries',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_series', to='tumor_api.patient'),
        ),
        migrations.AddField(
            model_name='imageseries',
            name='visit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image_series', to='tumor_api.visit'),
        ),
        migrations.AddField(
            model_name='dicomfile',
            name='series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dicom_files', to='tumor_api.imageseries'),
        ),
        migrations.AddIndex(
            model_name='imageseries',
            index=models.Index(fields=['patient', 'created_at'], name='tumor_api_i_patient_6d4d76_idx'),
        ),
        migrations.AddIndex(
            model_name='dicomfile',
            index=models.Index(fields=['series', 'created_at'], name='tumor_api_d_series__9cebfd_idx'),
        ),
    ]
