# Generated by Django 5.2.3 on 2025-06-14 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tumor_api', '0004_dicomfile_imageseries_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_type', models.CharField(db_index=True, max_length=50)),
                ('image_count', models.IntegerField()),
                ('summary', models.TextField(blank=True)),
                ('keyslices_dict', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
        ),
        migrations.RemoveIndex(
            model_name='llmoutputs',
            name='tumor_api_l_patient_69d54c_idx',
        ),
        migrations.RemoveField(
            model_name='imageseries',
            name='key_slices',
        ),
        migrations.AddField(
            model_name='imageseries',
            name='diagnostic_report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='diagnostic_report_image_series', to='tumor_api.diagnosticreport'),
        ),
        migrations.AlterField(
            model_name='imageseries',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_image_series', to='tumor_api.patient'),
        ),
        migrations.AlterField(
            model_name='imageseries',
            name='visit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visit_image_series', to='tumor_api.visit'),
        ),
        migrations.AddField(
            model_name='aireport',
            name='image_series',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_report', to='tumor_api.imageseries'),
        ),
        migrations.AddIndex(
            model_name='aireport',
            index=models.Index(fields=['image_series'], name='tumor_api_a_image_s_01b967_idx'),
        ),
    ]
